In [5]:
import itertools
import numpy as np

# ---------- GF(2) helpers ----------
def mod2(A): return (A % 2).astype(np.uint8)
def mmul(A,B): return mod2(A @ B)

def rank_gf2(M):
    M = (M.copy().astype(np.uint8) & 1)
    m,n = M.shape
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r,m):
            if M[i,c]:
                pivot = i; break
        if pivot is None:
            continue
        if pivot != r:
            M[[r,pivot]] = M[[pivot,r]]
        for i in range(m):
            if i != r and M[i,c]:
                M[i,:] ^= M[r,:]
        r += 1
        if r == m: break
    return r

# ---------- your matrices ----------
V1 = np.array([[0,1],[0,1],[0,0],[1,0]], dtype=np.uint8)
V2 = np.array([[1,1],[1,0],[0,1],[1,1]], dtype=np.uint8)
V3 = np.array([[0,0],[1,0],[1,1],[0,1]], dtype=np.uint8)
V4 = np.array([[0],[0],[1],[0]], dtype=np.uint8)
V5 = np.array([[0],[0],[0],[1]], dtype=np.uint8)

# ---------- GL(2,2) has 6 matrices ----------
GL2 = []
for a,b,c,d in itertools.product([0,1],[0,1],[0,1],[0,1]):
    det = (a*d) ^ (b*c)  # det over GF(2)
    if det == 1:
        GL2.append(np.array([[a,b],[c,d]], dtype=np.uint8))

def A_from(P1,P2,P3):
    A = mmul(mmul(V1,P1), V1.T)
    A ^= mmul(mmul(V2,P2), V2.T)
    A ^= mmul(mmul(V3,P3), V3.T)
    A ^= mmul(V4, V4.T)
    A ^= mmul(V5, V5.T)
    return A

min_rank = 99
bad = []
for P1 in GL2:
    for P2 in GL2:
        for P3 in GL2:
            A = A_from(P1,P2,P3)
            r = rank_gf2(A)
            min_rank = min(min_rank, r)
            if r <= 1:
                bad.append((P1,P2,P3,A,r))

print("min rank =", min_rank)
print("#cases with rank<=1 =", len(bad))


min rank = 2
#cases with rank<=1 = 0


In [9]:
print("printing each element of 2 by 2 matrix in F2:")
for i in range(len(GL2)):
  print(GL2[i])
  print("\n")


printing each element of 2 by 2 matrix in F2:
[[0 1]
 [1 0]]


[[0 1]
 [1 1]]


[[1 0]
 [0 1]]


[[1 0]
 [1 1]]


[[1 1]
 [0 1]]


[[1 1]
 [1 0]]




In [10]:

print("\nprinting each element of Vi:")
print("\nV1 =\n", V1)
print("\nV2 =\n", V2)
print("\nV3 =\n", V3)
print("\nV4 =\n", V4)
print("\nV5 =\n", V5)


printing each element of Vi:

V1 =
 [[0 1]
 [0 1]
 [0 0]
 [1 0]]

V2 =
 [[1 1]
 [1 0]
 [0 1]
 [1 1]]

V3 =
 [[0 0]
 [1 0]
 [1 1]
 [0 1]]

V4 =
 [[0]
 [0]
 [1]
 [0]]

V5 =
 [[0]
 [0]
 [0]
 [1]]
